# Example toolboxes taken from Bazzite
[arch]
image=ghcr.io/ublue-os/arch-toolbox:latest
pull=true

[debian]
image=quay.io/toolbx-images/debian-toolbox:unstable
pull=true

[fedora]
image=ghcr.io/ublue-os/fedora-toolbox:latest
pull=true
